default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dunder_mifflin_hr_development
  pool: 20
  username: danielwatson
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: dunder_mifflin_hr_test

production:
  <<: *default
  database: dkwatson522_final_production
  username: danielwatson
  password: <%= ENV['DKWATSON522_FINAL_DATABASE_PASSWORD'] %>
